// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BeginSongUploadArgs {
    pub project_id: u64,
    pub name: String,
    pub mime: String,
    pub byte_len: u64,
    pub num_chunks: u32,
    pub duration_ms: u32,
    pub fps_used: f32,
    pub beats_frames: Vec<u32>,
    pub bpm: f32,
    pub first_beat_ms: u32,
}

impl From<BeginSongUploadArgs> for super::Reducer {
    fn from(args: BeginSongUploadArgs) -> Self {
        Self::BeginSongUpload {
            project_id: args.project_id,
            name: args.name,
            mime: args.mime,
            byte_len: args.byte_len,
            num_chunks: args.num_chunks,
            duration_ms: args.duration_ms,
            fps_used: args.fps_used,
            beats_frames: args.beats_frames,
            bpm: args.bpm,
            first_beat_ms: args.first_beat_ms,
        }
    }
}

impl __sdk::InModule for BeginSongUploadArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `begin_song_upload`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait begin_song_upload {
    /// Request that the remote module invoke the reducer `begin_song_upload` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`begin_song_upload:begin_song_upload_then`] to run a callback after the reducer completes.
    fn begin_song_upload(
        &self,
        project_id: u64,
        name: String,
        mime: String,
        byte_len: u64,
        num_chunks: u32,
        duration_ms: u32,
        fps_used: f32,
        beats_frames: Vec<u32>,
        bpm: f32,
        first_beat_ms: u32,
    ) -> __sdk::Result<()> {
        self.begin_song_upload_then(
            project_id,
            name,
            mime,
            byte_len,
            num_chunks,
            duration_ms,
            fps_used,
            beats_frames,
            bpm,
            first_beat_ms,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `begin_song_upload` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn begin_song_upload_then(
        &self,
        project_id: u64,
        name: String,
        mime: String,
        byte_len: u64,
        num_chunks: u32,
        duration_ms: u32,
        fps_used: f32,
        beats_frames: Vec<u32>,
        bpm: f32,
        first_beat_ms: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl begin_song_upload for super::RemoteReducers {
    fn begin_song_upload_then(
        &self,
        project_id: u64,
        name: String,
        mime: String,
        byte_len: u64,
        num_chunks: u32,
        duration_ms: u32,
        fps_used: f32,
        beats_frames: Vec<u32>,
        bpm: f32,
        first_beat_ms: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            BeginSongUploadArgs {
                project_id,
                name,
                mime,
                byte_len,
                num_chunks,
                duration_ms,
                fps_used,
                beats_frames,
                bpm,
                first_beat_ms,
            },
            callback,
        )
    }
}
