// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteFixtureRegionArgs {
    pub project_id: u64,
    pub f_0: u32,
    pub f_1: u32,
    pub laser_channels: Vec<u8>,
    pub turret_channels: Vec<u8>,
    pub projector: bool,
}

impl From<DeleteFixtureRegionArgs> for super::Reducer {
    fn from(args: DeleteFixtureRegionArgs) -> Self {
        Self::DeleteFixtureRegion {
            project_id: args.project_id,
            f_0: args.f_0,
            f_1: args.f_1,
            laser_channels: args.laser_channels,
            turret_channels: args.turret_channels,
            projector: args.projector,
        }
    }
}

impl __sdk::InModule for DeleteFixtureRegionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `delete_fixture_region`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait delete_fixture_region {
    /// Request that the remote module invoke the reducer `delete_fixture_region` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`delete_fixture_region:delete_fixture_region_then`] to run a callback after the reducer completes.
    fn delete_fixture_region(
        &self,
        project_id: u64,
        f_0: u32,
        f_1: u32,
        laser_channels: Vec<u8>,
        turret_channels: Vec<u8>,
        projector: bool,
    ) -> __sdk::Result<()> {
        self.delete_fixture_region_then(
            project_id,
            f_0,
            f_1,
            laser_channels,
            turret_channels,
            projector,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `delete_fixture_region` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn delete_fixture_region_then(
        &self,
        project_id: u64,
        f_0: u32,
        f_1: u32,
        laser_channels: Vec<u8>,
        turret_channels: Vec<u8>,
        projector: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl delete_fixture_region for super::RemoteReducers {
    fn delete_fixture_region_then(
        &self,
        project_id: u64,
        f_0: u32,
        f_1: u32,
        laser_channels: Vec<u8>,
        turret_channels: Vec<u8>,
        projector: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DeleteFixtureRegionArgs {
                project_id,
                f_0,
                f_1,
                laser_channels,
                turret_channels,
                projector,
            },
            callback,
        )
    }
}
