// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Edit {
    pub id: u64,
    pub project_id: u64,
    pub seq: u64,
    pub author: __sdk::Identity,
    pub created_at: __sdk::Timestamp,
    pub light: u32,
    pub frame: u32,
    pub state: u8,
}

impl __sdk::InModule for Edit {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Edit`.
///
/// Provides typed access to columns for query building.
pub struct EditCols {
    pub id: __sdk::__query_builder::Col<Edit, u64>,
    pub project_id: __sdk::__query_builder::Col<Edit, u64>,
    pub seq: __sdk::__query_builder::Col<Edit, u64>,
    pub author: __sdk::__query_builder::Col<Edit, __sdk::Identity>,
    pub created_at: __sdk::__query_builder::Col<Edit, __sdk::Timestamp>,
    pub light: __sdk::__query_builder::Col<Edit, u32>,
    pub frame: __sdk::__query_builder::Col<Edit, u32>,
    pub state: __sdk::__query_builder::Col<Edit, u8>,
}

impl __sdk::__query_builder::HasCols for Edit {
    type Cols = EditCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EditCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            project_id: __sdk::__query_builder::Col::new(table_name, "project_id"),
            seq: __sdk::__query_builder::Col::new(table_name, "seq"),
            author: __sdk::__query_builder::Col::new(table_name, "author"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            light: __sdk::__query_builder::Col::new(table_name, "light"),
            frame: __sdk::__query_builder::Col::new(table_name, "frame"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
        }
    }
}

/// Indexed column accessor struct for the table `Edit`.
///
/// Provides typed access to indexed columns for query building.
pub struct EditIxCols {
    pub id: __sdk::__query_builder::IxCol<Edit, u64>,
    pub project_id: __sdk::__query_builder::IxCol<Edit, u64>,
}

impl __sdk::__query_builder::HasIxCols for Edit {
    type IxCols = EditIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EditIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            project_id: __sdk::__query_builder::IxCol::new(table_name, "project_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Edit {}
