// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ForkProjectArgs {
    pub project_id: u64,
}

impl From<ForkProjectArgs> for super::Reducer {
    fn from(args: ForkProjectArgs) -> Self {
        Self::ForkProject {
            project_id: args.project_id,
        }
    }
}

impl __sdk::InModule for ForkProjectArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `fork_project`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait fork_project {
    /// Request that the remote module invoke the reducer `fork_project` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`fork_project:fork_project_then`] to run a callback after the reducer completes.
    fn fork_project(&self, project_id: u64) -> __sdk::Result<()> {
        self.fork_project_then(project_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `fork_project` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn fork_project_then(
        &self,
        project_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl fork_project for super::RemoteReducers {
    fn fork_project_then(
        &self,
        project_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ForkProjectArgs { project_id }, callback)
    }
}
