// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct InsertBlueprintArgs {
    pub blueprint_id: u64,
    pub target_project_id: u64,
    pub base_light: u32,
    pub base_frame: u32,
}

impl From<InsertBlueprintArgs> for super::Reducer {
    fn from(args: InsertBlueprintArgs) -> Self {
        Self::InsertBlueprint {
            blueprint_id: args.blueprint_id,
            target_project_id: args.target_project_id,
            base_light: args.base_light,
            base_frame: args.base_frame,
        }
    }
}

impl __sdk::InModule for InsertBlueprintArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `insert_blueprint`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait insert_blueprint {
    /// Request that the remote module invoke the reducer `insert_blueprint` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`insert_blueprint:insert_blueprint_then`] to run a callback after the reducer completes.
    fn insert_blueprint(
        &self,
        blueprint_id: u64,
        target_project_id: u64,
        base_light: u32,
        base_frame: u32,
    ) -> __sdk::Result<()> {
        self.insert_blueprint_then(
            blueprint_id,
            target_project_id,
            base_light,
            base_frame,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `insert_blueprint` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn insert_blueprint_then(
        &self,
        blueprint_id: u64,
        target_project_id: u64,
        base_light: u32,
        base_frame: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl insert_blueprint for super::RemoteReducers {
    fn insert_blueprint_then(
        &self,
        blueprint_id: u64,
        target_project_id: u64,
        base_light: u32,
        base_frame: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            InsertBlueprintArgs {
                blueprint_id,
                target_project_id,
                base_light,
                base_frame,
            },
            callback,
        )
    }
}
