// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::laser_keyframe_type::LaserKeyframe;
use super::laser_point_type::LaserPoint;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `laser_kf`.
///
/// Obtain a handle from the [`LaserKfTableAccess::laser_kf`] method on [`super::RemoteTables`],
/// like `ctx.db.laser_kf()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.laser_kf().on_insert(...)`.
pub struct LaserKfTableHandle<'ctx> {
    imp: __sdk::TableHandle<LaserKeyframe>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `laser_kf`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LaserKfTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LaserKfTableHandle`], which mediates access to the table `laser_kf`.
    fn laser_kf(&self) -> LaserKfTableHandle<'_>;
}

impl LaserKfTableAccess for super::RemoteTables {
    fn laser_kf(&self) -> LaserKfTableHandle<'_> {
        LaserKfTableHandle {
            imp: self.imp.get_table::<LaserKeyframe>("laser_kf"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LaserKfInsertCallbackId(__sdk::CallbackId);
pub struct LaserKfDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LaserKfTableHandle<'ctx> {
    type Row = LaserKeyframe;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LaserKeyframe> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LaserKfInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LaserKfInsertCallbackId {
        LaserKfInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LaserKfInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LaserKfDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LaserKfDeleteCallbackId {
        LaserKfDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LaserKfDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct LaserKfUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LaserKfTableHandle<'ctx> {
    type UpdateCallbackId = LaserKfUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LaserKfUpdateCallbackId {
        LaserKfUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LaserKfUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `laser_kf`,
/// which allows point queries on the field of the same name
/// via the [`LaserKfIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.laser_kf().id().find(...)`.
pub struct LaserKfIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<LaserKeyframe, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LaserKfTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `laser_kf`.
    pub fn id(&self) -> LaserKfIdUnique<'ctx> {
        LaserKfIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LaserKfIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<LaserKeyframe> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LaserKeyframe>("laser_kf");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LaserKeyframe>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LaserKeyframe>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `LaserKeyframe`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait laser_kfQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `LaserKeyframe`.
    fn laser_kf(&self) -> __sdk::__query_builder::Table<LaserKeyframe>;
}

impl laser_kfQueryTableAccess for __sdk::QueryTableAccessor {
    fn laser_kf(&self) -> __sdk::__query_builder::Table<LaserKeyframe> {
        __sdk::__query_builder::Table::new("laser_kf")
    }
}
