// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::projector_keyframe_input_type::ProjectorKeyframeInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PasteProjectorKeyframesArgs {
    pub project_id: u64,
    pub rows: Vec<ProjectorKeyframeInput>,
}

impl From<PasteProjectorKeyframesArgs> for super::Reducer {
    fn from(args: PasteProjectorKeyframesArgs) -> Self {
        Self::PasteProjectorKeyframes {
            project_id: args.project_id,
            rows: args.rows,
        }
    }
}

impl __sdk::InModule for PasteProjectorKeyframesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `paste_projector_keyframes`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait paste_projector_keyframes {
    /// Request that the remote module invoke the reducer `paste_projector_keyframes` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`paste_projector_keyframes:paste_projector_keyframes_then`] to run a callback after the reducer completes.
    fn paste_projector_keyframes(
        &self,
        project_id: u64,
        rows: Vec<ProjectorKeyframeInput>,
    ) -> __sdk::Result<()> {
        self.paste_projector_keyframes_then(project_id, rows, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `paste_projector_keyframes` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn paste_projector_keyframes_then(
        &self,
        project_id: u64,
        rows: Vec<ProjectorKeyframeInput>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl paste_projector_keyframes for super::RemoteReducers {
    fn paste_projector_keyframes_then(
        &self,
        project_id: u64,
        rows: Vec<ProjectorKeyframeInput>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PasteProjectorKeyframesArgs { project_id, rows },
            callback,
        )
    }
}
