// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::laser_point_type::LaserPoint;
use super::pattern_type::Pattern;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `pattern`.
///
/// Obtain a handle from the [`PatternTableAccess::pattern`] method on [`super::RemoteTables`],
/// like `ctx.db.pattern()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.pattern().on_insert(...)`.
pub struct PatternTableHandle<'ctx> {
    imp: __sdk::TableHandle<Pattern>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `pattern`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PatternTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PatternTableHandle`], which mediates access to the table `pattern`.
    fn pattern(&self) -> PatternTableHandle<'_>;
}

impl PatternTableAccess for super::RemoteTables {
    fn pattern(&self) -> PatternTableHandle<'_> {
        PatternTableHandle {
            imp: self.imp.get_table::<Pattern>("pattern"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PatternInsertCallbackId(__sdk::CallbackId);
pub struct PatternDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PatternTableHandle<'ctx> {
    type Row = Pattern;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Pattern> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PatternInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PatternInsertCallbackId {
        PatternInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PatternInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PatternDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PatternDeleteCallbackId {
        PatternDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PatternDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PatternUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PatternTableHandle<'ctx> {
    type UpdateCallbackId = PatternUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PatternUpdateCallbackId {
        PatternUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PatternUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `pattern`,
/// which allows point queries on the field of the same name
/// via the [`PatternIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.pattern().id().find(...)`.
pub struct PatternIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Pattern, u8>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PatternTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `pattern`.
    pub fn id(&self) -> PatternIdUnique<'ctx> {
        PatternIdUnique {
            imp: self.imp.get_unique_constraint::<u8>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PatternIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u8) -> Option<Pattern> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Pattern>("pattern");
    _table.add_unique_constraint::<u8>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Pattern>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Pattern>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Pattern`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait patternQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Pattern`.
    fn pattern(&self) -> __sdk::__query_builder::Table<Pattern>;
}

impl patternQueryTableAccess for __sdk::QueryTableAccessor {
    fn pattern(&self) -> __sdk::__query_builder::Table<Pattern> {
        __sdk::__query_builder::Table::new("pattern")
    }
}
