// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ProjectorKeyframeInput {
    pub frame: u32,
    pub channel: u8,
    pub state: u8,
    pub gallery: u8,
    pub pattern: u8,
    pub colour: u8,
}

impl __sdk::InModule for ProjectorKeyframeInput {
    type Module = super::RemoteModule;
}
