// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Project {
    pub id: u64,
    pub owner: __sdk::Identity,
    pub name: String,
    pub num_lights: u32,
    pub num_frames: u32,
    pub created_at: __sdk::Timestamp,
    pub head_seq: u64,
    pub is_template: bool,
    pub is_blueprint: bool,
}

impl __sdk::InModule for Project {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Project`.
///
/// Provides typed access to columns for query building.
pub struct ProjectCols {
    pub id: __sdk::__query_builder::Col<Project, u64>,
    pub owner: __sdk::__query_builder::Col<Project, __sdk::Identity>,
    pub name: __sdk::__query_builder::Col<Project, String>,
    pub num_lights: __sdk::__query_builder::Col<Project, u32>,
    pub num_frames: __sdk::__query_builder::Col<Project, u32>,
    pub created_at: __sdk::__query_builder::Col<Project, __sdk::Timestamp>,
    pub head_seq: __sdk::__query_builder::Col<Project, u64>,
    pub is_template: __sdk::__query_builder::Col<Project, bool>,
    pub is_blueprint: __sdk::__query_builder::Col<Project, bool>,
}

impl __sdk::__query_builder::HasCols for Project {
    type Cols = ProjectCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ProjectCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            num_lights: __sdk::__query_builder::Col::new(table_name, "num_lights"),
            num_frames: __sdk::__query_builder::Col::new(table_name, "num_frames"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            head_seq: __sdk::__query_builder::Col::new(table_name, "head_seq"),
            is_template: __sdk::__query_builder::Col::new(table_name, "is_template"),
            is_blueprint: __sdk::__query_builder::Col::new(table_name, "is_blueprint"),
        }
    }
}

/// Indexed column accessor struct for the table `Project`.
///
/// Provides typed access to indexed columns for query building.
pub struct ProjectIxCols {
    pub id: __sdk::__query_builder::IxCol<Project, u64>,
}

impl __sdk::__query_builder::HasIxCols for Project {
    type IxCols = ProjectIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ProjectIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Project {}
