// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::projector_keyframe_type::ProjectorKeyframe;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `projector_kf`.
///
/// Obtain a handle from the [`ProjectorKfTableAccess::projector_kf`] method on [`super::RemoteTables`],
/// like `ctx.db.projector_kf()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.projector_kf().on_insert(...)`.
pub struct ProjectorKfTableHandle<'ctx> {
    imp: __sdk::TableHandle<ProjectorKeyframe>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `projector_kf`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ProjectorKfTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ProjectorKfTableHandle`], which mediates access to the table `projector_kf`.
    fn projector_kf(&self) -> ProjectorKfTableHandle<'_>;
}

impl ProjectorKfTableAccess for super::RemoteTables {
    fn projector_kf(&self) -> ProjectorKfTableHandle<'_> {
        ProjectorKfTableHandle {
            imp: self.imp.get_table::<ProjectorKeyframe>("projector_kf"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ProjectorKfInsertCallbackId(__sdk::CallbackId);
pub struct ProjectorKfDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ProjectorKfTableHandle<'ctx> {
    type Row = ProjectorKeyframe;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ProjectorKeyframe> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ProjectorKfInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ProjectorKfInsertCallbackId {
        ProjectorKfInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ProjectorKfInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ProjectorKfDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ProjectorKfDeleteCallbackId {
        ProjectorKfDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ProjectorKfDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ProjectorKfUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ProjectorKfTableHandle<'ctx> {
    type UpdateCallbackId = ProjectorKfUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ProjectorKfUpdateCallbackId {
        ProjectorKfUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ProjectorKfUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `projector_kf`,
/// which allows point queries on the field of the same name
/// via the [`ProjectorKfIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.projector_kf().id().find(...)`.
pub struct ProjectorKfIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ProjectorKeyframe, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ProjectorKfTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `projector_kf`.
    pub fn id(&self) -> ProjectorKfIdUnique<'ctx> {
        ProjectorKfIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ProjectorKfIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ProjectorKeyframe> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ProjectorKeyframe>("projector_kf");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ProjectorKeyframe>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ProjectorKeyframe>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ProjectorKeyframe`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait projector_kfQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ProjectorKeyframe`.
    fn projector_kf(&self) -> __sdk::__query_builder::Table<ProjectorKeyframe>;
}

impl projector_kfQueryTableAccess for __sdk::QueryTableAccessor {
    fn projector_kf(&self) -> __sdk::__query_builder::Table<ProjectorKeyframe> {
        __sdk::__query_builder::Table::new("projector_kf")
    }
}
