// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ProjectorKeyframe {
    pub id: u64,
    pub project_id: u64,
    pub frame: u32,
    pub channel: u8,
    pub state: u8,
    pub gallery: u8,
    pub pattern: u8,
    pub colour: u8,
}

impl __sdk::InModule for ProjectorKeyframe {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ProjectorKeyframe`.
///
/// Provides typed access to columns for query building.
pub struct ProjectorKeyframeCols {
    pub id: __sdk::__query_builder::Col<ProjectorKeyframe, u64>,
    pub project_id: __sdk::__query_builder::Col<ProjectorKeyframe, u64>,
    pub frame: __sdk::__query_builder::Col<ProjectorKeyframe, u32>,
    pub channel: __sdk::__query_builder::Col<ProjectorKeyframe, u8>,
    pub state: __sdk::__query_builder::Col<ProjectorKeyframe, u8>,
    pub gallery: __sdk::__query_builder::Col<ProjectorKeyframe, u8>,
    pub pattern: __sdk::__query_builder::Col<ProjectorKeyframe, u8>,
    pub colour: __sdk::__query_builder::Col<ProjectorKeyframe, u8>,
}

impl __sdk::__query_builder::HasCols for ProjectorKeyframe {
    type Cols = ProjectorKeyframeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ProjectorKeyframeCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            project_id: __sdk::__query_builder::Col::new(table_name, "project_id"),
            frame: __sdk::__query_builder::Col::new(table_name, "frame"),
            channel: __sdk::__query_builder::Col::new(table_name, "channel"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
            gallery: __sdk::__query_builder::Col::new(table_name, "gallery"),
            pattern: __sdk::__query_builder::Col::new(table_name, "pattern"),
            colour: __sdk::__query_builder::Col::new(table_name, "colour"),
        }
    }
}

/// Indexed column accessor struct for the table `ProjectorKeyframe`.
///
/// Provides typed access to indexed columns for query building.
pub struct ProjectorKeyframeIxCols {
    pub id: __sdk::__query_builder::IxCol<ProjectorKeyframe, u64>,
    pub project_id: __sdk::__query_builder::IxCol<ProjectorKeyframe, u64>,
}

impl __sdk::__query_builder::HasIxCols for ProjectorKeyframe {
    type IxCols = ProjectorKeyframeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ProjectorKeyframeIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            project_id: __sdk::__query_builder::IxCol::new(table_name, "project_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ProjectorKeyframe {}
