// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedSongArgs {
    pub name: String,
    pub song_name: String,
    pub mime: String,
    pub byte_len: u64,
    pub num_chunks: u32,
    pub duration_ms: u32,
    pub fps_used: f32,
    pub beats_frames: Vec<u32>,
    pub bpm: f32,
    pub first_beat_ms: u32,
}

impl From<SeedSongArgs> for super::Reducer {
    fn from(args: SeedSongArgs) -> Self {
        Self::SeedSong {
            name: args.name,
            song_name: args.song_name,
            mime: args.mime,
            byte_len: args.byte_len,
            num_chunks: args.num_chunks,
            duration_ms: args.duration_ms,
            fps_used: args.fps_used,
            beats_frames: args.beats_frames,
            bpm: args.bpm,
            first_beat_ms: args.first_beat_ms,
        }
    }
}

impl __sdk::InModule for SeedSongArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_song`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_song {
    /// Request that the remote module invoke the reducer `seed_song` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_song:seed_song_then`] to run a callback after the reducer completes.
    fn seed_song(
        &self,
        name: String,
        song_name: String,
        mime: String,
        byte_len: u64,
        num_chunks: u32,
        duration_ms: u32,
        fps_used: f32,
        beats_frames: Vec<u32>,
        bpm: f32,
        first_beat_ms: u32,
    ) -> __sdk::Result<()> {
        self.seed_song_then(
            name,
            song_name,
            mime,
            byte_len,
            num_chunks,
            duration_ms,
            fps_used,
            beats_frames,
            bpm,
            first_beat_ms,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `seed_song` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_song_then(
        &self,
        name: String,
        song_name: String,
        mime: String,
        byte_len: u64,
        num_chunks: u32,
        duration_ms: u32,
        fps_used: f32,
        beats_frames: Vec<u32>,
        bpm: f32,
        first_beat_ms: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_song for super::RemoteReducers {
    fn seed_song_then(
        &self,
        name: String,
        song_name: String,
        mime: String,
        byte_len: u64,
        num_chunks: u32,
        duration_ms: u32,
        fps_used: f32,
        beats_frames: Vec<u32>,
        bpm: f32,
        first_beat_ms: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SeedSongArgs {
                name,
                song_name,
                mime,
                byte_len,
                num_chunks,
                duration_ms,
                fps_used,
                beats_frames,
                bpm,
                first_beat_ms,
            },
            callback,
        )
    }
}
