// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetProjectorKeyframeArgs {
    pub project_id: u64,
    pub frame: u32,
    pub channel: u8,
    pub state: u8,
    pub gallery: u8,
    pub pattern: u8,
    pub colour: u8,
}

impl From<SetProjectorKeyframeArgs> for super::Reducer {
    fn from(args: SetProjectorKeyframeArgs) -> Self {
        Self::SetProjectorKeyframe {
            project_id: args.project_id,
            frame: args.frame,
            channel: args.channel,
            state: args.state,
            gallery: args.gallery,
            pattern: args.pattern,
            colour: args.colour,
        }
    }
}

impl __sdk::InModule for SetProjectorKeyframeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_projector_keyframe`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_projector_keyframe {
    /// Request that the remote module invoke the reducer `set_projector_keyframe` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_projector_keyframe:set_projector_keyframe_then`] to run a callback after the reducer completes.
    fn set_projector_keyframe(
        &self,
        project_id: u64,
        frame: u32,
        channel: u8,
        state: u8,
        gallery: u8,
        pattern: u8,
        colour: u8,
    ) -> __sdk::Result<()> {
        self.set_projector_keyframe_then(
            project_id,
            frame,
            channel,
            state,
            gallery,
            pattern,
            colour,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `set_projector_keyframe` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_projector_keyframe_then(
        &self,
        project_id: u64,
        frame: u32,
        channel: u8,
        state: u8,
        gallery: u8,
        pattern: u8,
        colour: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_projector_keyframe for super::RemoteReducers {
    fn set_projector_keyframe_then(
        &self,
        project_id: u64,
        frame: u32,
        channel: u8,
        state: u8,
        gallery: u8,
        pattern: u8,
        colour: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetProjectorKeyframeArgs {
                project_id,
                frame,
                channel,
                state,
                gallery,
                pattern,
                colour,
            },
            callback,
        )
    }
}
