// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SongChunk {
    pub id: u64,
    pub song_id: u64,
    pub project_id: u64,
    pub idx: u32,
    pub data: Vec<u8>,
}

impl __sdk::InModule for SongChunk {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SongChunk`.
///
/// Provides typed access to columns for query building.
pub struct SongChunkCols {
    pub id: __sdk::__query_builder::Col<SongChunk, u64>,
    pub song_id: __sdk::__query_builder::Col<SongChunk, u64>,
    pub project_id: __sdk::__query_builder::Col<SongChunk, u64>,
    pub idx: __sdk::__query_builder::Col<SongChunk, u32>,
    pub data: __sdk::__query_builder::Col<SongChunk, Vec<u8>>,
}

impl __sdk::__query_builder::HasCols for SongChunk {
    type Cols = SongChunkCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SongChunkCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            song_id: __sdk::__query_builder::Col::new(table_name, "song_id"),
            project_id: __sdk::__query_builder::Col::new(table_name, "project_id"),
            idx: __sdk::__query_builder::Col::new(table_name, "idx"),
            data: __sdk::__query_builder::Col::new(table_name, "data"),
        }
    }
}

/// Indexed column accessor struct for the table `SongChunk`.
///
/// Provides typed access to indexed columns for query building.
pub struct SongChunkIxCols {
    pub id: __sdk::__query_builder::IxCol<SongChunk, u64>,
    pub song_id: __sdk::__query_builder::IxCol<SongChunk, u64>,
}

impl __sdk::__query_builder::HasIxCols for SongChunk {
    type IxCols = SongChunkIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SongChunkIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            song_id: __sdk::__query_builder::IxCol::new(table_name, "song_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SongChunk {}
