// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::song_chunk_type::SongChunk;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `song_chunk`.
///
/// Obtain a handle from the [`SongChunkTableAccess::song_chunk`] method on [`super::RemoteTables`],
/// like `ctx.db.song_chunk()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.song_chunk().on_insert(...)`.
pub struct SongChunkTableHandle<'ctx> {
    imp: __sdk::TableHandle<SongChunk>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `song_chunk`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SongChunkTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SongChunkTableHandle`], which mediates access to the table `song_chunk`.
    fn song_chunk(&self) -> SongChunkTableHandle<'_>;
}

impl SongChunkTableAccess for super::RemoteTables {
    fn song_chunk(&self) -> SongChunkTableHandle<'_> {
        SongChunkTableHandle {
            imp: self.imp.get_table::<SongChunk>("song_chunk"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SongChunkInsertCallbackId(__sdk::CallbackId);
pub struct SongChunkDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SongChunkTableHandle<'ctx> {
    type Row = SongChunk;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SongChunk> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SongChunkInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SongChunkInsertCallbackId {
        SongChunkInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SongChunkInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SongChunkDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SongChunkDeleteCallbackId {
        SongChunkDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SongChunkDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SongChunkUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SongChunkTableHandle<'ctx> {
    type UpdateCallbackId = SongChunkUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SongChunkUpdateCallbackId {
        SongChunkUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SongChunkUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `song_chunk`,
/// which allows point queries on the field of the same name
/// via the [`SongChunkIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.song_chunk().id().find(...)`.
pub struct SongChunkIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SongChunk, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SongChunkTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `song_chunk`.
    pub fn id(&self) -> SongChunkIdUnique<'ctx> {
        SongChunkIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SongChunkIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SongChunk> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SongChunk>("song_chunk");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SongChunk>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SongChunk>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SongChunk`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait song_chunkQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SongChunk`.
    fn song_chunk(&self) -> __sdk::__query_builder::Table<SongChunk>;
}

impl song_chunkQueryTableAccess for __sdk::QueryTableAccessor {
    fn song_chunk(&self) -> __sdk::__query_builder::Table<SongChunk> {
        __sdk::__query_builder::Table::new("song_chunk")
    }
}
