// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::song_type::Song;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `song`.
///
/// Obtain a handle from the [`SongTableAccess::song`] method on [`super::RemoteTables`],
/// like `ctx.db.song()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.song().on_insert(...)`.
pub struct SongTableHandle<'ctx> {
    imp: __sdk::TableHandle<Song>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `song`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SongTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SongTableHandle`], which mediates access to the table `song`.
    fn song(&self) -> SongTableHandle<'_>;
}

impl SongTableAccess for super::RemoteTables {
    fn song(&self) -> SongTableHandle<'_> {
        SongTableHandle {
            imp: self.imp.get_table::<Song>("song"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SongInsertCallbackId(__sdk::CallbackId);
pub struct SongDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SongTableHandle<'ctx> {
    type Row = Song;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Song> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SongInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SongInsertCallbackId {
        SongInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SongInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SongDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SongDeleteCallbackId {
        SongDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SongDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SongUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SongTableHandle<'ctx> {
    type UpdateCallbackId = SongUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SongUpdateCallbackId {
        SongUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SongUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `song`,
/// which allows point queries on the field of the same name
/// via the [`SongIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.song().id().find(...)`.
pub struct SongIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Song, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SongTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `song`.
    pub fn id(&self) -> SongIdUnique<'ctx> {
        SongIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SongIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Song> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Song>("song");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Song>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Song>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Song`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait songQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Song`.
    fn song(&self) -> __sdk::__query_builder::Table<Song>;
}

impl songQueryTableAccess for __sdk::QueryTableAccessor {
    fn song(&self) -> __sdk::__query_builder::Table<Song> {
        __sdk::__query_builder::Table::new("song")
    }
}
