// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::turret_keyframe_type::TurretKeyframe;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `turret_kf`.
///
/// Obtain a handle from the [`TurretKfTableAccess::turret_kf`] method on [`super::RemoteTables`],
/// like `ctx.db.turret_kf()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.turret_kf().on_insert(...)`.
pub struct TurretKfTableHandle<'ctx> {
    imp: __sdk::TableHandle<TurretKeyframe>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `turret_kf`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TurretKfTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TurretKfTableHandle`], which mediates access to the table `turret_kf`.
    fn turret_kf(&self) -> TurretKfTableHandle<'_>;
}

impl TurretKfTableAccess for super::RemoteTables {
    fn turret_kf(&self) -> TurretKfTableHandle<'_> {
        TurretKfTableHandle {
            imp: self.imp.get_table::<TurretKeyframe>("turret_kf"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TurretKfInsertCallbackId(__sdk::CallbackId);
pub struct TurretKfDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TurretKfTableHandle<'ctx> {
    type Row = TurretKeyframe;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TurretKeyframe> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TurretKfInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TurretKfInsertCallbackId {
        TurretKfInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TurretKfInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TurretKfDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TurretKfDeleteCallbackId {
        TurretKfDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TurretKfDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TurretKfUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TurretKfTableHandle<'ctx> {
    type UpdateCallbackId = TurretKfUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TurretKfUpdateCallbackId {
        TurretKfUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TurretKfUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `turret_kf`,
/// which allows point queries on the field of the same name
/// via the [`TurretKfIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.turret_kf().id().find(...)`.
pub struct TurretKfIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TurretKeyframe, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TurretKfTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `turret_kf`.
    pub fn id(&self) -> TurretKfIdUnique<'ctx> {
        TurretKfIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TurretKfIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TurretKeyframe> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TurretKeyframe>("turret_kf");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TurretKeyframe>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TurretKeyframe>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TurretKeyframe`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait turret_kfQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TurretKeyframe`.
    fn turret_kf(&self) -> __sdk::__query_builder::Table<TurretKeyframe>;
}

impl turret_kfQueryTableAccess for __sdk::QueryTableAccessor {
    fn turret_kf(&self) -> __sdk::__query_builder::Table<TurretKeyframe> {
        __sdk::__query_builder::Table::new("turret_kf")
    }
}
