// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::light_edit_input_type::LightEditInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AppendEditsArgs {
    pub project_id: u64,
    pub edits: Vec<LightEditInput>,
}

impl From<AppendEditsArgs> for super::Reducer {
    fn from(args: AppendEditsArgs) -> Self {
        Self::AppendEdits {
            project_id: args.project_id,
            edits: args.edits,
        }
    }
}

impl __sdk::InModule for AppendEditsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `append_edits`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait append_edits {
    /// Request that the remote module invoke the reducer `append_edits` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`append_edits:append_edits_then`] to run a callback after the reducer completes.
    fn append_edits(&self, project_id: u64, edits: Vec<LightEditInput>) -> __sdk::Result<()> {
        self.append_edits_then(project_id, edits, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `append_edits` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn append_edits_then(
        &self,
        project_id: u64,
        edits: Vec<LightEditInput>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl append_edits for super::RemoteReducers {
    fn append_edits_then(
        &self,
        project_id: u64,
        edits: Vec<LightEditInput>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AppendEditsArgs { project_id, edits }, callback)
    }
}
