// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AppendSongChunkArgs {
    pub song_id: u64,
    pub idx: u32,
    pub data: Vec<u8>,
}

impl From<AppendSongChunkArgs> for super::Reducer {
    fn from(args: AppendSongChunkArgs) -> Self {
        Self::AppendSongChunk {
            song_id: args.song_id,
            idx: args.idx,
            data: args.data,
        }
    }
}

impl __sdk::InModule for AppendSongChunkArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `append_song_chunk`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait append_song_chunk {
    /// Request that the remote module invoke the reducer `append_song_chunk` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`append_song_chunk:append_song_chunk_then`] to run a callback after the reducer completes.
    fn append_song_chunk(&self, song_id: u64, idx: u32, data: Vec<u8>) -> __sdk::Result<()> {
        self.append_song_chunk_then(song_id, idx, data, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `append_song_chunk` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn append_song_chunk_then(
        &self,
        song_id: u64,
        idx: u32,
        data: Vec<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl append_song_chunk for super::RemoteReducers {
    fn append_song_chunk_then(
        &self,
        song_id: u64,
        idx: u32,
        data: Vec<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AppendSongChunkArgs { song_id, idx, data }, callback)
    }
}
