// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::edit_type::Edit;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `edit_log`.
///
/// Obtain a handle from the [`EditLogTableAccess::edit_log`] method on [`super::RemoteTables`],
/// like `ctx.db.edit_log()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.edit_log().on_insert(...)`.
pub struct EditLogTableHandle<'ctx> {
    imp: __sdk::TableHandle<Edit>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `edit_log`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EditLogTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EditLogTableHandle`], which mediates access to the table `edit_log`.
    fn edit_log(&self) -> EditLogTableHandle<'_>;
}

impl EditLogTableAccess for super::RemoteTables {
    fn edit_log(&self) -> EditLogTableHandle<'_> {
        EditLogTableHandle {
            imp: self.imp.get_table::<Edit>("edit_log"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EditLogInsertCallbackId(__sdk::CallbackId);
pub struct EditLogDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for EditLogTableHandle<'ctx> {
    type Row = Edit;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Edit> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EditLogInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EditLogInsertCallbackId {
        EditLogInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EditLogInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EditLogDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EditLogDeleteCallbackId {
        EditLogDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EditLogDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct EditLogUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for EditLogTableHandle<'ctx> {
    type UpdateCallbackId = EditLogUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EditLogUpdateCallbackId {
        EditLogUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EditLogUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `edit_log`,
/// which allows point queries on the field of the same name
/// via the [`EditLogIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.edit_log().id().find(...)`.
pub struct EditLogIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Edit, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EditLogTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `edit_log`.
    pub fn id(&self) -> EditLogIdUnique<'ctx> {
        EditLogIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EditLogIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Edit> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Edit>("edit_log");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Edit>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Edit>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Edit`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait edit_logQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Edit`.
    fn edit_log(&self) -> __sdk::__query_builder::Table<Edit>;
}

impl edit_logQueryTableAccess for __sdk::QueryTableAccessor {
    fn edit_log(&self) -> __sdk::__query_builder::Table<Edit> {
        __sdk::__query_builder::Table::new("edit_log")
    }
}
