// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::laser_point_type::LaserPoint;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LaserKeyframe {
    pub id: u64,
    pub project_id: u64,
    pub frame: u32,
    pub channel: u8,
    pub enable: bool,
    pub pattern: u8,
    pub points: Vec<LaserPoint>,
    pub cr: u8,
    pub cg: u8,
    pub cb: u8,
}

impl __sdk::InModule for LaserKeyframe {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LaserKeyframe`.
///
/// Provides typed access to columns for query building.
pub struct LaserKeyframeCols {
    pub id: __sdk::__query_builder::Col<LaserKeyframe, u64>,
    pub project_id: __sdk::__query_builder::Col<LaserKeyframe, u64>,
    pub frame: __sdk::__query_builder::Col<LaserKeyframe, u32>,
    pub channel: __sdk::__query_builder::Col<LaserKeyframe, u8>,
    pub enable: __sdk::__query_builder::Col<LaserKeyframe, bool>,
    pub pattern: __sdk::__query_builder::Col<LaserKeyframe, u8>,
    pub points: __sdk::__query_builder::Col<LaserKeyframe, Vec<LaserPoint>>,
    pub cr: __sdk::__query_builder::Col<LaserKeyframe, u8>,
    pub cg: __sdk::__query_builder::Col<LaserKeyframe, u8>,
    pub cb: __sdk::__query_builder::Col<LaserKeyframe, u8>,
}

impl __sdk::__query_builder::HasCols for LaserKeyframe {
    type Cols = LaserKeyframeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LaserKeyframeCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            project_id: __sdk::__query_builder::Col::new(table_name, "project_id"),
            frame: __sdk::__query_builder::Col::new(table_name, "frame"),
            channel: __sdk::__query_builder::Col::new(table_name, "channel"),
            enable: __sdk::__query_builder::Col::new(table_name, "enable"),
            pattern: __sdk::__query_builder::Col::new(table_name, "pattern"),
            points: __sdk::__query_builder::Col::new(table_name, "points"),
            cr: __sdk::__query_builder::Col::new(table_name, "cr"),
            cg: __sdk::__query_builder::Col::new(table_name, "cg"),
            cb: __sdk::__query_builder::Col::new(table_name, "cb"),
        }
    }
}

/// Indexed column accessor struct for the table `LaserKeyframe`.
///
/// Provides typed access to indexed columns for query building.
pub struct LaserKeyframeIxCols {
    pub id: __sdk::__query_builder::IxCol<LaserKeyframe, u64>,
    pub project_id: __sdk::__query_builder::IxCol<LaserKeyframe, u64>,
}

impl __sdk::__query_builder::HasIxCols for LaserKeyframe {
    type IxCols = LaserKeyframeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LaserKeyframeIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            project_id: __sdk::__query_builder::IxCol::new(table_name, "project_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LaserKeyframe {}
