// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::laser_point_type::LaserPoint;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LaserKeyframeInput {
    pub frame: u32,
    pub channel: u8,
    pub enable: bool,
    pub pattern: u8,
    pub cr: u8,
    pub cg: u8,
    pub cb: u8,
    pub points: Vec<LaserPoint>,
}

impl __sdk::InModule for LaserKeyframeInput {
    type Module = super::RemoteModule;
}
