// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.5.0 (commit 19cbf2b219ac9fd7fdca6c5e2c61a3a2f0319515).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod append_edit_reducer;
pub mod append_song_chunk_reducer;
pub mod begin_song_upload_reducer;
pub mod create_project_reducer;
pub mod delete_song_reducer;
pub mod edit_log_table;
pub mod edit_type;
pub mod fork_project_reducer;
pub mod laser_keyframe_input_type;
pub mod laser_keyframe_type;
pub mod laser_kf_table;
pub mod laser_point_type;
pub mod light_edit_input_type;
pub mod project_table;
pub mod project_type;
pub mod projector_keyframe_input_type;
pub mod projector_keyframe_type;
pub mod projector_kf_table;
pub mod seed_laser_keyframes_reducer;
pub mod seed_light_edits_reducer;
pub mod seed_project_reducer;
pub mod seed_projector_keyframes_reducer;
pub mod seed_song_chunk_reducer;
pub mod seed_song_reducer;
pub mod seed_turret_keyframes_reducer;
pub mod song_chunk_table;
pub mod song_chunk_type;
pub mod song_table;
pub mod song_type;
pub mod turret_keyframe_input_type;
pub mod turret_keyframe_type;
pub mod turret_kf_table;

pub use append_edit_reducer::append_edit;
pub use append_song_chunk_reducer::append_song_chunk;
pub use begin_song_upload_reducer::begin_song_upload;
pub use create_project_reducer::create_project;
pub use delete_song_reducer::delete_song;
pub use edit_log_table::*;
pub use edit_type::Edit;
pub use fork_project_reducer::fork_project;
pub use laser_keyframe_input_type::LaserKeyframeInput;
pub use laser_keyframe_type::LaserKeyframe;
pub use laser_kf_table::*;
pub use laser_point_type::LaserPoint;
pub use light_edit_input_type::LightEditInput;
pub use project_table::*;
pub use project_type::Project;
pub use projector_keyframe_input_type::ProjectorKeyframeInput;
pub use projector_keyframe_type::ProjectorKeyframe;
pub use projector_kf_table::*;
pub use seed_laser_keyframes_reducer::seed_laser_keyframes;
pub use seed_light_edits_reducer::seed_light_edits;
pub use seed_project_reducer::seed_project;
pub use seed_projector_keyframes_reducer::seed_projector_keyframes;
pub use seed_song_chunk_reducer::seed_song_chunk;
pub use seed_song_reducer::seed_song;
pub use seed_turret_keyframes_reducer::seed_turret_keyframes;
pub use song_chunk_table::*;
pub use song_chunk_type::SongChunk;
pub use song_table::*;
pub use song_type::Song;
pub use turret_keyframe_input_type::TurretKeyframeInput;
pub use turret_keyframe_type::TurretKeyframe;
pub use turret_kf_table::*;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    AppendEdit {
        project_id: u64,
        light: u32,
        frame: u32,
        state: u8,
    },
    AppendSongChunk {
        song_id: u64,
        idx: u32,
        data: Vec<u8>,
    },
    BeginSongUpload {
        project_id: u64,
        name: String,
        mime: String,
        byte_len: u64,
        num_chunks: u32,
        duration_ms: u32,
        fps_used: f32,
        beats_frames: Vec<u32>,
        bpm: f32,
        first_beat_ms: u32,
    },
    CreateProject {
        name: String,
        num_lights: u32,
        num_frames: u32,
    },
    DeleteSong {
        project_id: u64,
    },
    ForkProject {
        project_id: u64,
    },
    SeedLaserKeyframes {
        name: String,
        rows: Vec<LaserKeyframeInput>,
    },
    SeedLightEdits {
        name: String,
        edits: Vec<LightEditInput>,
    },
    SeedProject {
        name: String,
        num_lights: u32,
        num_frames: u32,
    },
    SeedProjectorKeyframes {
        name: String,
        rows: Vec<ProjectorKeyframeInput>,
    },
    SeedSong {
        name: String,
        song_name: String,
        mime: String,
        byte_len: u64,
        num_chunks: u32,
        duration_ms: u32,
        fps_used: f32,
        beats_frames: Vec<u32>,
        bpm: f32,
        first_beat_ms: u32,
    },
    SeedSongChunk {
        name: String,
        idx: u32,
        data: Vec<u8>,
    },
    SeedTurretKeyframes {
        name: String,
        rows: Vec<TurretKeyframeInput>,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::AppendEdit { .. } => "append_edit",
            Reducer::AppendSongChunk { .. } => "append_song_chunk",
            Reducer::BeginSongUpload { .. } => "begin_song_upload",
            Reducer::CreateProject { .. } => "create_project",
            Reducer::DeleteSong { .. } => "delete_song",
            Reducer::ForkProject { .. } => "fork_project",
            Reducer::SeedLaserKeyframes { .. } => "seed_laser_keyframes",
            Reducer::SeedLightEdits { .. } => "seed_light_edits",
            Reducer::SeedProject { .. } => "seed_project",
            Reducer::SeedProjectorKeyframes { .. } => "seed_projector_keyframes",
            Reducer::SeedSong { .. } => "seed_song",
            Reducer::SeedSongChunk { .. } => "seed_song_chunk",
            Reducer::SeedTurretKeyframes { .. } => "seed_turret_keyframes",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::AppendEdit {
                project_id,
                light,
                frame,
                state,
            } => __sats::bsatn::to_vec(&append_edit_reducer::AppendEditArgs {
                project_id: project_id.clone(),
                light: light.clone(),
                frame: frame.clone(),
                state: state.clone(),
            }),
            Reducer::AppendSongChunk { song_id, idx, data } => {
                __sats::bsatn::to_vec(&append_song_chunk_reducer::AppendSongChunkArgs {
                    song_id: song_id.clone(),
                    idx: idx.clone(),
                    data: data.clone(),
                })
            }
            Reducer::BeginSongUpload {
                project_id,
                name,
                mime,
                byte_len,
                num_chunks,
                duration_ms,
                fps_used,
                beats_frames,
                bpm,
                first_beat_ms,
            } => __sats::bsatn::to_vec(&begin_song_upload_reducer::BeginSongUploadArgs {
                project_id: project_id.clone(),
                name: name.clone(),
                mime: mime.clone(),
                byte_len: byte_len.clone(),
                num_chunks: num_chunks.clone(),
                duration_ms: duration_ms.clone(),
                fps_used: fps_used.clone(),
                beats_frames: beats_frames.clone(),
                bpm: bpm.clone(),
                first_beat_ms: first_beat_ms.clone(),
            }),
            Reducer::CreateProject {
                name,
                num_lights,
                num_frames,
            } => __sats::bsatn::to_vec(&create_project_reducer::CreateProjectArgs {
                name: name.clone(),
                num_lights: num_lights.clone(),
                num_frames: num_frames.clone(),
            }),
            Reducer::DeleteSong { project_id } => {
                __sats::bsatn::to_vec(&delete_song_reducer::DeleteSongArgs {
                    project_id: project_id.clone(),
                })
            }
            Reducer::ForkProject { project_id } => {
                __sats::bsatn::to_vec(&fork_project_reducer::ForkProjectArgs {
                    project_id: project_id.clone(),
                })
            }
            Reducer::SeedLaserKeyframes { name, rows } => {
                __sats::bsatn::to_vec(&seed_laser_keyframes_reducer::SeedLaserKeyframesArgs {
                    name: name.clone(),
                    rows: rows.clone(),
                })
            }
            Reducer::SeedLightEdits { name, edits } => {
                __sats::bsatn::to_vec(&seed_light_edits_reducer::SeedLightEditsArgs {
                    name: name.clone(),
                    edits: edits.clone(),
                })
            }
            Reducer::SeedProject {
                name,
                num_lights,
                num_frames,
            } => __sats::bsatn::to_vec(&seed_project_reducer::SeedProjectArgs {
                name: name.clone(),
                num_lights: num_lights.clone(),
                num_frames: num_frames.clone(),
            }),
            Reducer::SeedProjectorKeyframes { name, rows } => __sats::bsatn::to_vec(
                &seed_projector_keyframes_reducer::SeedProjectorKeyframesArgs {
                    name: name.clone(),
                    rows: rows.clone(),
                },
            ),
            Reducer::SeedSong {
                name,
                song_name,
                mime,
                byte_len,
                num_chunks,
                duration_ms,
                fps_used,
                beats_frames,
                bpm,
                first_beat_ms,
            } => __sats::bsatn::to_vec(&seed_song_reducer::SeedSongArgs {
                name: name.clone(),
                song_name: song_name.clone(),
                mime: mime.clone(),
                byte_len: byte_len.clone(),
                num_chunks: num_chunks.clone(),
                duration_ms: duration_ms.clone(),
                fps_used: fps_used.clone(),
                beats_frames: beats_frames.clone(),
                bpm: bpm.clone(),
                first_beat_ms: first_beat_ms.clone(),
            }),
            Reducer::SeedSongChunk { name, idx, data } => {
                __sats::bsatn::to_vec(&seed_song_chunk_reducer::SeedSongChunkArgs {
                    name: name.clone(),
                    idx: idx.clone(),
                    data: data.clone(),
                })
            }
            Reducer::SeedTurretKeyframes { name, rows } => {
                __sats::bsatn::to_vec(&seed_turret_keyframes_reducer::SeedTurretKeyframesArgs {
                    name: name.clone(),
                    rows: rows.clone(),
                })
            }
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    edit_log: __sdk::TableUpdate<Edit>,
    laser_kf: __sdk::TableUpdate<LaserKeyframe>,
    project: __sdk::TableUpdate<Project>,
    projector_kf: __sdk::TableUpdate<ProjectorKeyframe>,
    song: __sdk::TableUpdate<Song>,
    song_chunk: __sdk::TableUpdate<SongChunk>,
    turret_kf: __sdk::TableUpdate<TurretKeyframe>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "edit_log" => db_update
                    .edit_log
                    .append(edit_log_table::parse_table_update(table_update)?),
                "laser_kf" => db_update
                    .laser_kf
                    .append(laser_kf_table::parse_table_update(table_update)?),
                "project" => db_update
                    .project
                    .append(project_table::parse_table_update(table_update)?),
                "projector_kf" => db_update
                    .projector_kf
                    .append(projector_kf_table::parse_table_update(table_update)?),
                "song" => db_update
                    .song
                    .append(song_table::parse_table_update(table_update)?),
                "song_chunk" => db_update
                    .song_chunk
                    .append(song_chunk_table::parse_table_update(table_update)?),
                "turret_kf" => db_update
                    .turret_kf
                    .append(turret_kf_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.edit_log = cache
            .apply_diff_to_table::<Edit>("edit_log", &self.edit_log)
            .with_updates_by_pk(|row| &row.id);
        diff.laser_kf = cache
            .apply_diff_to_table::<LaserKeyframe>("laser_kf", &self.laser_kf)
            .with_updates_by_pk(|row| &row.id);
        diff.project = cache
            .apply_diff_to_table::<Project>("project", &self.project)
            .with_updates_by_pk(|row| &row.id);
        diff.projector_kf = cache
            .apply_diff_to_table::<ProjectorKeyframe>("projector_kf", &self.projector_kf)
            .with_updates_by_pk(|row| &row.id);
        diff.song = cache
            .apply_diff_to_table::<Song>("song", &self.song)
            .with_updates_by_pk(|row| &row.id);
        diff.song_chunk = cache
            .apply_diff_to_table::<SongChunk>("song_chunk", &self.song_chunk)
            .with_updates_by_pk(|row| &row.id);
        diff.turret_kf = cache
            .apply_diff_to_table::<TurretKeyframe>("turret_kf", &self.turret_kf)
            .with_updates_by_pk(|row| &row.id);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "edit_log" => db_update
                    .edit_log
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "laser_kf" => db_update
                    .laser_kf
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "project" => db_update
                    .project
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "projector_kf" => db_update
                    .projector_kf
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "song" => db_update
                    .song
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "song_chunk" => db_update
                    .song_chunk
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "turret_kf" => db_update
                    .turret_kf
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "edit_log" => db_update
                    .edit_log
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "laser_kf" => db_update
                    .laser_kf
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "project" => db_update
                    .project
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "projector_kf" => db_update
                    .projector_kf
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "song" => db_update
                    .song
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "song_chunk" => db_update
                    .song_chunk
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "turret_kf" => db_update
                    .turret_kf
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    edit_log: __sdk::TableAppliedDiff<'r, Edit>,
    laser_kf: __sdk::TableAppliedDiff<'r, LaserKeyframe>,
    project: __sdk::TableAppliedDiff<'r, Project>,
    projector_kf: __sdk::TableAppliedDiff<'r, ProjectorKeyframe>,
    song: __sdk::TableAppliedDiff<'r, Song>,
    song_chunk: __sdk::TableAppliedDiff<'r, SongChunk>,
    turret_kf: __sdk::TableAppliedDiff<'r, TurretKeyframe>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<Edit>("edit_log", &self.edit_log, event);
        callbacks.invoke_table_row_callbacks::<LaserKeyframe>("laser_kf", &self.laser_kf, event);
        callbacks.invoke_table_row_callbacks::<Project>("project", &self.project, event);
        callbacks.invoke_table_row_callbacks::<ProjectorKeyframe>(
            "projector_kf",
            &self.projector_kf,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Song>("song", &self.song, event);
        callbacks.invoke_table_row_callbacks::<SongChunk>("song_chunk", &self.song_chunk, event);
        callbacks.invoke_table_row_callbacks::<TurretKeyframe>("turret_kf", &self.turret_kf, event);
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        edit_log_table::register_table(client_cache);
        laser_kf_table::register_table(client_cache);
        project_table::register_table(client_cache);
        projector_kf_table::register_table(client_cache);
        song_table::register_table(client_cache);
        song_chunk_table::register_table(client_cache);
        turret_kf_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "edit_log",
        "laser_kf",
        "project",
        "projector_kf",
        "song",
        "song_chunk",
        "turret_kf",
    ];
}
