// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::laser_keyframe_input_type::LaserKeyframeInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PasteLaserKeyframesArgs {
    pub project_id: u64,
    pub rows: Vec<LaserKeyframeInput>,
}

impl From<PasteLaserKeyframesArgs> for super::Reducer {
    fn from(args: PasteLaserKeyframesArgs) -> Self {
        Self::PasteLaserKeyframes {
            project_id: args.project_id,
            rows: args.rows,
        }
    }
}

impl __sdk::InModule for PasteLaserKeyframesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `paste_laser_keyframes`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait paste_laser_keyframes {
    /// Request that the remote module invoke the reducer `paste_laser_keyframes` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`paste_laser_keyframes:paste_laser_keyframes_then`] to run a callback after the reducer completes.
    fn paste_laser_keyframes(
        &self,
        project_id: u64,
        rows: Vec<LaserKeyframeInput>,
    ) -> __sdk::Result<()> {
        self.paste_laser_keyframes_then(project_id, rows, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `paste_laser_keyframes` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn paste_laser_keyframes_then(
        &self,
        project_id: u64,
        rows: Vec<LaserKeyframeInput>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl paste_laser_keyframes for super::RemoteReducers {
    fn paste_laser_keyframes_then(
        &self,
        project_id: u64,
        rows: Vec<LaserKeyframeInput>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(PasteLaserKeyframesArgs { project_id, rows }, callback)
    }
}
