// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::laser_point_type::LaserPoint;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Pattern {
    pub id: u8,
    pub name: String,
    pub points: Vec<LaserPoint>,
}

impl __sdk::InModule for Pattern {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Pattern`.
///
/// Provides typed access to columns for query building.
pub struct PatternCols {
    pub id: __sdk::__query_builder::Col<Pattern, u8>,
    pub name: __sdk::__query_builder::Col<Pattern, String>,
    pub points: __sdk::__query_builder::Col<Pattern, Vec<LaserPoint>>,
}

impl __sdk::__query_builder::HasCols for Pattern {
    type Cols = PatternCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PatternCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            points: __sdk::__query_builder::Col::new(table_name, "points"),
        }
    }
}

/// Indexed column accessor struct for the table `Pattern`.
///
/// Provides typed access to indexed columns for query building.
pub struct PatternIxCols {
    pub id: __sdk::__query_builder::IxCol<Pattern, u8>,
}

impl __sdk::__query_builder::HasIxCols for Pattern {
    type IxCols = PatternIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PatternIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Pattern {}
