// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::laser_keyframe_input_type::LaserKeyframeInput;
use super::light_edit_input_type::LightEditInput;
use super::projector_keyframe_input_type::ProjectorKeyframeInput;
use super::turret_keyframe_input_type::TurretKeyframeInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SaveBlueprintArgs {
    pub name: String,
    pub num_lights: u32,
    pub num_frames: u32,
    pub light_edits: Vec<LightEditInput>,
    pub lasers: Vec<LaserKeyframeInput>,
    pub projectors: Vec<ProjectorKeyframeInput>,
    pub turrets: Vec<TurretKeyframeInput>,
}

impl From<SaveBlueprintArgs> for super::Reducer {
    fn from(args: SaveBlueprintArgs) -> Self {
        Self::SaveBlueprint {
            name: args.name,
            num_lights: args.num_lights,
            num_frames: args.num_frames,
            light_edits: args.light_edits,
            lasers: args.lasers,
            projectors: args.projectors,
            turrets: args.turrets,
        }
    }
}

impl __sdk::InModule for SaveBlueprintArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `save_blueprint`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait save_blueprint {
    /// Request that the remote module invoke the reducer `save_blueprint` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`save_blueprint:save_blueprint_then`] to run a callback after the reducer completes.
    fn save_blueprint(
        &self,
        name: String,
        num_lights: u32,
        num_frames: u32,
        light_edits: Vec<LightEditInput>,
        lasers: Vec<LaserKeyframeInput>,
        projectors: Vec<ProjectorKeyframeInput>,
        turrets: Vec<TurretKeyframeInput>,
    ) -> __sdk::Result<()> {
        self.save_blueprint_then(
            name,
            num_lights,
            num_frames,
            light_edits,
            lasers,
            projectors,
            turrets,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `save_blueprint` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn save_blueprint_then(
        &self,
        name: String,
        num_lights: u32,
        num_frames: u32,
        light_edits: Vec<LightEditInput>,
        lasers: Vec<LaserKeyframeInput>,
        projectors: Vec<ProjectorKeyframeInput>,
        turrets: Vec<TurretKeyframeInput>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl save_blueprint for super::RemoteReducers {
    fn save_blueprint_then(
        &self,
        name: String,
        num_lights: u32,
        num_frames: u32,
        light_edits: Vec<LightEditInput>,
        lasers: Vec<LaserKeyframeInput>,
        projectors: Vec<ProjectorKeyframeInput>,
        turrets: Vec<TurretKeyframeInput>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SaveBlueprintArgs {
                name,
                num_lights,
                num_frames,
                light_edits,
                lasers,
                projectors,
                turrets,
            },
            callback,
        )
    }
}
