// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::laser_point_type::LaserPoint;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedPatternArgs {
    pub id: u8,
    pub name: String,
    pub points: Vec<LaserPoint>,
}

impl From<SeedPatternArgs> for super::Reducer {
    fn from(args: SeedPatternArgs) -> Self {
        Self::SeedPattern {
            id: args.id,
            name: args.name,
            points: args.points,
        }
    }
}

impl __sdk::InModule for SeedPatternArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_pattern`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_pattern {
    /// Request that the remote module invoke the reducer `seed_pattern` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_pattern:seed_pattern_then`] to run a callback after the reducer completes.
    fn seed_pattern(&self, id: u8, name: String, points: Vec<LaserPoint>) -> __sdk::Result<()> {
        self.seed_pattern_then(id, name, points, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `seed_pattern` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_pattern_then(
        &self,
        id: u8,
        name: String,
        points: Vec<LaserPoint>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_pattern for super::RemoteReducers {
    fn seed_pattern_then(
        &self,
        id: u8,
        name: String,
        points: Vec<LaserPoint>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SeedPatternArgs { id, name, points }, callback)
    }
}
