// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::laser_keyframe_input_type::LaserKeyframeInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SeedLaserKeyframesArgs {
    pub name: String,
    pub rows: Vec<LaserKeyframeInput>,
}

impl From<SeedLaserKeyframesArgs> for super::Reducer {
    fn from(args: SeedLaserKeyframesArgs) -> Self {
        Self::SeedLaserKeyframes {
            name: args.name,
            rows: args.rows,
        }
    }
}

impl __sdk::InModule for SeedLaserKeyframesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `seed_laser_keyframes`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait seed_laser_keyframes {
    /// Request that the remote module invoke the reducer `seed_laser_keyframes` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`seed_laser_keyframes:seed_laser_keyframes_then`] to run a callback after the reducer completes.
    fn seed_laser_keyframes(
        &self,
        name: String,
        rows: Vec<LaserKeyframeInput>,
    ) -> __sdk::Result<()> {
        self.seed_laser_keyframes_then(name, rows, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `seed_laser_keyframes` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn seed_laser_keyframes_then(
        &self,
        name: String,
        rows: Vec<LaserKeyframeInput>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl seed_laser_keyframes for super::RemoteReducers {
    fn seed_laser_keyframes_then(
        &self,
        name: String,
        rows: Vec<LaserKeyframeInput>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SeedLaserKeyframesArgs { name, rows }, callback)
    }
}
