// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetLaserKeyframeArgs {
    pub project_id: u64,
    pub frame: u32,
    pub channel: u8,
    pub enable: bool,
    pub pattern: u8,
    pub cr: u8,
    pub cg: u8,
    pub cb: u8,
}

impl From<SetLaserKeyframeArgs> for super::Reducer {
    fn from(args: SetLaserKeyframeArgs) -> Self {
        Self::SetLaserKeyframe {
            project_id: args.project_id,
            frame: args.frame,
            channel: args.channel,
            enable: args.enable,
            pattern: args.pattern,
            cr: args.cr,
            cg: args.cg,
            cb: args.cb,
        }
    }
}

impl __sdk::InModule for SetLaserKeyframeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_laser_keyframe`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_laser_keyframe {
    /// Request that the remote module invoke the reducer `set_laser_keyframe` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_laser_keyframe:set_laser_keyframe_then`] to run a callback after the reducer completes.
    fn set_laser_keyframe(
        &self,
        project_id: u64,
        frame: u32,
        channel: u8,
        enable: bool,
        pattern: u8,
        cr: u8,
        cg: u8,
        cb: u8,
    ) -> __sdk::Result<()> {
        self.set_laser_keyframe_then(
            project_id,
            frame,
            channel,
            enable,
            pattern,
            cr,
            cg,
            cb,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `set_laser_keyframe` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_laser_keyframe_then(
        &self,
        project_id: u64,
        frame: u32,
        channel: u8,
        enable: bool,
        pattern: u8,
        cr: u8,
        cg: u8,
        cb: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_laser_keyframe for super::RemoteReducers {
    fn set_laser_keyframe_then(
        &self,
        project_id: u64,
        frame: u32,
        channel: u8,
        enable: bool,
        pattern: u8,
        cr: u8,
        cg: u8,
        cb: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetLaserKeyframeArgs {
                project_id,
                frame,
                channel,
                enable,
                pattern,
                cr,
                cg,
                cb,
            },
            callback,
        )
    }
}
