// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetTurretKeyframeArgs {
    pub project_id: u64,
    pub frame: u32,
    pub channel: u8,
    pub state: u8,
    pub pan: u8,
    pub tilt: u8,
}

impl From<SetTurretKeyframeArgs> for super::Reducer {
    fn from(args: SetTurretKeyframeArgs) -> Self {
        Self::SetTurretKeyframe {
            project_id: args.project_id,
            frame: args.frame,
            channel: args.channel,
            state: args.state,
            pan: args.pan,
            tilt: args.tilt,
        }
    }
}

impl __sdk::InModule for SetTurretKeyframeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_turret_keyframe`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_turret_keyframe {
    /// Request that the remote module invoke the reducer `set_turret_keyframe` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_turret_keyframe:set_turret_keyframe_then`] to run a callback after the reducer completes.
    fn set_turret_keyframe(
        &self,
        project_id: u64,
        frame: u32,
        channel: u8,
        state: u8,
        pan: u8,
        tilt: u8,
    ) -> __sdk::Result<()> {
        self.set_turret_keyframe_then(project_id, frame, channel, state, pan, tilt, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_turret_keyframe` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_turret_keyframe_then(
        &self,
        project_id: u64,
        frame: u32,
        channel: u8,
        state: u8,
        pan: u8,
        tilt: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_turret_keyframe for super::RemoteReducers {
    fn set_turret_keyframe_then(
        &self,
        project_id: u64,
        frame: u32,
        channel: u8,
        state: u8,
        pan: u8,
        tilt: u8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetTurretKeyframeArgs {
                project_id,
                frame,
                channel,
                state,
                pan,
                tilt,
            },
            callback,
        )
    }
}
