// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Song {
    pub id: u64,
    pub project_id: u64,
    pub owner: __sdk::Identity,
    pub name: String,
    pub mime: String,
    pub byte_len: u64,
    pub num_chunks: u32,
    pub chunks_received: u32,
    pub duration_ms: u32,
    pub fps_used: f32,
    pub beats_frames: Vec<u32>,
    pub bpm: f32,
    pub first_beat_ms: u32,
    pub complete: bool,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for Song {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Song`.
///
/// Provides typed access to columns for query building.
pub struct SongCols {
    pub id: __sdk::__query_builder::Col<Song, u64>,
    pub project_id: __sdk::__query_builder::Col<Song, u64>,
    pub owner: __sdk::__query_builder::Col<Song, __sdk::Identity>,
    pub name: __sdk::__query_builder::Col<Song, String>,
    pub mime: __sdk::__query_builder::Col<Song, String>,
    pub byte_len: __sdk::__query_builder::Col<Song, u64>,
    pub num_chunks: __sdk::__query_builder::Col<Song, u32>,
    pub chunks_received: __sdk::__query_builder::Col<Song, u32>,
    pub duration_ms: __sdk::__query_builder::Col<Song, u32>,
    pub fps_used: __sdk::__query_builder::Col<Song, f32>,
    pub beats_frames: __sdk::__query_builder::Col<Song, Vec<u32>>,
    pub bpm: __sdk::__query_builder::Col<Song, f32>,
    pub first_beat_ms: __sdk::__query_builder::Col<Song, u32>,
    pub complete: __sdk::__query_builder::Col<Song, bool>,
    pub created_at: __sdk::__query_builder::Col<Song, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Song {
    type Cols = SongCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SongCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            project_id: __sdk::__query_builder::Col::new(table_name, "project_id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            mime: __sdk::__query_builder::Col::new(table_name, "mime"),
            byte_len: __sdk::__query_builder::Col::new(table_name, "byte_len"),
            num_chunks: __sdk::__query_builder::Col::new(table_name, "num_chunks"),
            chunks_received: __sdk::__query_builder::Col::new(table_name, "chunks_received"),
            duration_ms: __sdk::__query_builder::Col::new(table_name, "duration_ms"),
            fps_used: __sdk::__query_builder::Col::new(table_name, "fps_used"),
            beats_frames: __sdk::__query_builder::Col::new(table_name, "beats_frames"),
            bpm: __sdk::__query_builder::Col::new(table_name, "bpm"),
            first_beat_ms: __sdk::__query_builder::Col::new(table_name, "first_beat_ms"),
            complete: __sdk::__query_builder::Col::new(table_name, "complete"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Song`.
///
/// Provides typed access to indexed columns for query building.
pub struct SongIxCols {
    pub id: __sdk::__query_builder::IxCol<Song, u64>,
    pub project_id: __sdk::__query_builder::IxCol<Song, u64>,
}

impl __sdk::__query_builder::HasIxCols for Song {
    type IxCols = SongIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SongIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            project_id: __sdk::__query_builder::IxCol::new(table_name, "project_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Song {}
