// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TurretKeyframe {
    pub id: u64,
    pub project_id: u64,
    pub frame: u32,
    pub channel: u8,
    pub state: u8,
    pub pan: u8,
    pub tilt: u8,
}

impl __sdk::InModule for TurretKeyframe {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TurretKeyframe`.
///
/// Provides typed access to columns for query building.
pub struct TurretKeyframeCols {
    pub id: __sdk::__query_builder::Col<TurretKeyframe, u64>,
    pub project_id: __sdk::__query_builder::Col<TurretKeyframe, u64>,
    pub frame: __sdk::__query_builder::Col<TurretKeyframe, u32>,
    pub channel: __sdk::__query_builder::Col<TurretKeyframe, u8>,
    pub state: __sdk::__query_builder::Col<TurretKeyframe, u8>,
    pub pan: __sdk::__query_builder::Col<TurretKeyframe, u8>,
    pub tilt: __sdk::__query_builder::Col<TurretKeyframe, u8>,
}

impl __sdk::__query_builder::HasCols for TurretKeyframe {
    type Cols = TurretKeyframeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TurretKeyframeCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            project_id: __sdk::__query_builder::Col::new(table_name, "project_id"),
            frame: __sdk::__query_builder::Col::new(table_name, "frame"),
            channel: __sdk::__query_builder::Col::new(table_name, "channel"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
            pan: __sdk::__query_builder::Col::new(table_name, "pan"),
            tilt: __sdk::__query_builder::Col::new(table_name, "tilt"),
        }
    }
}

/// Indexed column accessor struct for the table `TurretKeyframe`.
///
/// Provides typed access to indexed columns for query building.
pub struct TurretKeyframeIxCols {
    pub id: __sdk::__query_builder::IxCol<TurretKeyframe, u64>,
    pub project_id: __sdk::__query_builder::IxCol<TurretKeyframe, u64>,
}

impl __sdk::__query_builder::HasIxCols for TurretKeyframe {
    type IxCols = TurretKeyframeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TurretKeyframeIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            project_id: __sdk::__query_builder::IxCol::new(table_name, "project_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TurretKeyframe {}
